//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activnosti
    {
        public Activnosti()
        {
            this.Activnost_Merop = new HashSet<Activnost_Merop>();
            this.Merop_Zhuri = new HashSet<Merop_Zhuri>();
        }
    
        public int Id_activnosti { get; set; }
        public string Nazvanie { get; set; }
    
        public virtual ICollection<Activnost_Merop> Activnost_Merop { get; set; }
        public virtual ICollection<Merop_Zhuri> Merop_Zhuri { get; set; }
    }
}
