//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activnost_Merop
    {
        public int Id_activnosti { get; set; }
        public int Id_meropriyatiya { get; set; }
        public int Data_provedeniya { get; set; }
        public System.TimeSpan Vremya { get; set; }
        public int Id_moderator { get; set; }
    
        public virtual Activnosti Activnosti { get; set; }
        public virtual Meropriyatiya Meropriyatiya { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
    }
}
