//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goroda
    {
        public Goroda()
        {
            this.Meropriyatiya = new HashSet<Meropriyatiya>();
        }
    
        public int Id_gorod { get; set; }
        public string Nazvanie { get; set; }
        public string Ssilka { get; set; }
    
        public virtual ICollection<Meropriyatiya> Meropriyatiya { get; set; }
    }
}
