//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeropriyatiyaMainW
    {
        public int Id_meropriyatiya { get; set; }
        public string Nazvanie { get; set; }
        public System.DateTime Data_nachala { get; set; }
        public string Expr1 { get; set; }
        public string Logo
        {
            get
            {
                return $"/Images/{Id_meropriyatiya}.jpg";
            }
        }
    }
}
