//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merop_TipMerop_Napravl
    {
        public int Id_meropriyatiya { get; set; }
        public int Id_tip_meropriyatiya { get; set; }
        public int Id_napravlenie { get; set; }
    
        public virtual Meropriyatiya Meropriyatiya { get; set; }
        public virtual Napravlenie Napravlenie { get; set; }
        public virtual Tip_meropriyatiya Tip_meropriyatiya { get; set; }
    }
}
