//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPraktika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bbbbbEntities : DbContext
    {
        public bbbbbEntities()
            : base("name=bbbbbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activnost_Merop> Activnost_Merop { get; set; }
        public DbSet<Activnosti> Activnosti { get; set; }
        public DbSet<Goroda> Goroda { get; set; }
        public DbSet<Merop_TipMerop_Napravl> Merop_TipMerop_Napravl { get; set; }
        public DbSet<Merop_Uchastnik> Merop_Uchastnik { get; set; }
        public DbSet<Merop_Zhuri> Merop_Zhuri { get; set; }
        public DbSet<Meropriyatiya> Meropriyatiya { get; set; }
        public DbSet<Napravlenie> Napravlenie { get; set; }
        public DbSet<Polzovateli> Polzovateli { get; set; }
        public DbSet<Roli> Roli { get; set; }
        public DbSet<Strani> Strani { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tip_meropriyatiya> Tip_meropriyatiya { get; set; }
        public DbSet<MeropriyatiyaMainW> MeropriyatiyaMainW { get; set; }
    }
}
