//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strani
    {
        public int Id1 { get; set; }
        public string Id2 { get; set; }
        public string Nazvanie { get; set; }
        public string Nazvanie_Angl { get; set; }
    }
}
