//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip_meropriyatiya
    {
        public Tip_meropriyatiya()
        {
            this.Merop_TipMerop_Napravl = new HashSet<Merop_TipMerop_Napravl>();
        }
    
        public int Id_tip_meropriyatiya { get; set; }
        public string Nazvanie { get; set; }
    
        public virtual ICollection<Merop_TipMerop_Napravl> Merop_TipMerop_Napravl { get; set; }
    }
}
